Add ispyb.model.samplegroup
DiamondLightSource/ispyb-api pull request #104
Opened 2020-08-03 14:38 UTC by rjgildea

New ispyb.model.samplegroup.SampleGroup model. Provides access to
associated sample ids and dcids.

New property DataCollection.sample_groups which returns a list of
SampleGroup objects associated with the current DataCollection.

2020-08-04 08:18 UTC, Anthchirp requested changes

2020-08-04 08:18 UTC, Anthchirp commented on ispyb/model/__future__.py
> +def _get_sample_group(self):
Can we either add a JIRA ticket or add the line
```suggestion
def _get_sample_group(self):
    # not yet requested
```
This allows us to see at a glance what the status of all the `future` methods is

2020-08-04 08:18 UTC, Anthchirp commented on ispyb/model/__future__.py
> +def _get_linked_sample_groups_for_dcid(self):
as above

2020-08-24 10:47 UTC, KarlLevik approved these changes

2020-08-24 10:47 UTC, merged